version: '3.9'

networks:
  algafood-network:
    driver: bridge

services:
  algafood-mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    networks:
      - algafood-network